version: "3.8"
services:
  etcd:
    image: quay.io/coreos/etcd:v3.4.27
    entrypoint: 
      - /usr/local/bin/etcd 
      - --advertise-client-urls
      - http://0.0.0.0:2379
      - --listen-client-urls
      - http://0.0.0.0:2379
      - --data-dir
      - /etcd-data
    # uncomment the lines below (and the volume declaration under $.volumes.etcd-data) to persist application data
    # volumes:
    #   - etcd-data:/etcd-data
    networks:
      - internal

  kube-apiserver:
    image: registry.k8s.io/kube-apiserver:v1.27.4
    depends_on:
      etcd:
        condition: service_started
      bootstrap-certs:
        condition: service_completed_successfully
    entrypoint:
      - /usr/local/bin/kube-apiserver
      - --etcd-servers=http://etcd:2379
      - --bind-address=0.0.0.0
      - --service-cluster-ip-range=10.0.0.0/24
      - --authorization-mode=AlwaysAllow
      - --service-account-issuer=https://kube-apiserver:6443
      - --service-account-key-file=/etc/keyfiles/service-account.crt
      - --service-account-signing-key-file=/etc/keyfiles/service-account.key
      - --token-auth-file=/etc/kubernetes/tokenfile.csv
      - --tls-cert-file=/etc/keyfiles/apiserver.crt
      - --tls-private-key-file=/etc/keyfiles/apiserver.key
      - --cors-allowed-origins=.*
    volumes:
      - key-files:/etc/keyfiles
      - ./files/tokenfile.csv:/etc/kubernetes/tokenfile.csv
    networks:
      - internal

  bootstrap-certs:
    image: finalgene/openssh:9.1
    entrypoint: 
      - bash
      - /usr/scripts/bootstrap-certs
    environment:
      CERT_DIR: /etc/keyfiles
      TEMP_DIR: /tmp/keyfiles
    volumes:
      - key-files:/etc/keyfiles
      - ./scripts:/usr/scripts

  bootstrap-apiserver:
    image: bitnami/kubectl:1.27.4
    depends_on:
      kube-apiserver:
        condition: service_started
    entrypoint:
      - bash
      - /usr/bootstrap-apiserver/run
    volumes:
      - ./bootstrap-apiserver:/usr/bootstrap-apiserver
      - key-files:/etc/keyfiles
    networks:
      - internal

  webserver:
    image: nginx:1.21.3
    ports:
      - 8080:80
    volumes:
      - ./www:/usr/share/nginx/html
      - key-files:/etc/keyfiles
      - ./files/nginx.conf:/etc/nginx/nginx.conf
    entrypoint:
      - nginx
      - -g
      - daemon off;
    networks:
      - internal

volumes:
  key-files: {}
  # etcd-data: {} # uncomment this line (and $.services.etcd.volumes[*]) to persist application data

networks:
  internal:
    driver: bridge
