#!/usr/bin/env bash
set -euo pipefail

temp_dir=$1
cd "${temp_dir}"

cat > nginx-csr.json <<EOF
{
  "CN": "kubernetes",
  "key": {
    "algo": "rsa",
    "size": 2048
  },
  "names": [
    {
      "C": "US",
      "L": "Portland",
      "O": "Kubernetes",
      "OU": "nginx",
      "ST": "Oregon"
    }
  ]
}
EOF

cfssl gencert \
  -ca=ca.pem \
  -ca-key=ca-key.pem \
  -config=ca-config.json \
  -hostname=localhost,webserver \
  -profile=kubernetes \
  nginx-csr.json | cfssljson -bare nginx
