#!/usr/bin/env bash
set -euo pipefail

temp_dir=$1
cd "${temp_dir}"

cat > openssl.cnf <<EOF
[req]
default_bits = 2048
prompt = no
default_md = sha256
distinguished_name = dn

[dn]
CN = Kubernetes
EOF

echo "Generating CA key and certificate"

openssl genrsa -out ca.key 2048
openssl req -new -key ca.key -out ca-csr.crt -config openssl.cnf
openssl x509 -req -in ca-csr.crt -signkey ca.key -out ca.crt -days 365 -sha256