#!/usr/bin/env bash
set -euo pipefail

temp_dir=$1
cd "${temp_dir}"

cat > service-account-csr.conf <<EOF
[req]
default_bits = 2048
prompt = no
default_md = sha256
distinguished_name = dn

[dn]
CN = service-accounts
EOF

echo "Generating service account key and certificate"

openssl genrsa -out service-account.key 2048
openssl req -new -key service-account.key -out service-account-csr.crt -config service-account-csr.conf
openssl x509 -req -in service-account-csr.crt -CA ca.crt -CAkey ca.key -CAcreateserial -out service-account.crt -days 365 -sha256