#!/usr/bin/env bash
set -euo pipefail

temp_dir=$1
cd "${temp_dir}"

cat > openssl.cnf <<EOF
[req]
default_bits = 2048
prompt = no
default_md = sha256
distinguished_name = dn

[dn]
CN = kube-apiserver

[req_ext]
subjectAltName = @alt_names

[alt_names]
DNS.1 = kube-apiserver
DNS.2 = kubernetes
DNS.3 = kubernetes.default
DNS.4 = kubernetes.default.svc
DNS.5 = kubernetes.default.svc.cluster
DNS.6 = kubernetes.svc.cluster.local
EOF

echo "Generating API server key and certificate"

openssl genrsa -out apiserver.key 2048
openssl req -new -key apiserver.key -out apiserver-csr.crt -config openssl.cnf
openssl x509 -req -in apiserver-csr.crt -CA ca.crt -CAkey ca.key -CAcreateserial -out apiserver.crt -days 365 -sha256 -extensions req_ext -extfile openssl.cnf